run_name: unet_StepLR
base_output_dir: training_runs
class_names:
- Road (tarmac)
- Road marks
- Painted metal
- Sky
- Concrete/stone/brick
model:
    name: HybridUNet
    params:
        in_channels: 25
        selected_channels: 15
        num_classes: 5
        bilinear: true
        base_filters: 64
data:
    dir: Image_dataset
    normalization: z-score
    patching:
        patch_size: 384
        stride: 192
    class_mapping:
        1: 0
        2: 1
        4: 2
        5: 3
        6: 4
        0: 0
        3: 2
        7: 2
        9: 2
        10: 4
augmentation:
    elastic_transform:
        p: 0.5
        alpha: 120
        sigma: 6
    shift_scale_rotate:
        p: 0.7
        shift_limit: 0.0625
        scale_limit: 0.1
        rotate_limit: 15
    random_brightness_contrast:
        p: 0.3
    gauss_noise:
        p: 0.2
training:
    batch_size: 16
    num_epochs: 40
    early_stopping_patience: 25
optimizer:
    name: AdamW
    params:
        lr: 0.0001
        weight_decay: 0.0001
scheduler:
    name: StepLR
    params:
        step_size: 30
        gamma: 0.1
loss:
    name: WeightedCombinedLoss
    boundary_weight:
        w0: 10.0
        sigma: 5.0
    params:
        alpha: 1.0
        beta: 0.5
