run_name: run8_re-experiment_300_epochs_5_channels_trainable_band_selector_bs32_dep5
base_output_dir: ./training_runs
class_names:
- background
- road
- building
- water
- vegetation
- unlabeled
data:
    dir: Image_dataset
    normalization: z-score
    class_mapping:
        0: 0
        1: 1
        2: 2
        3: 3
        4: 4
        5: 5
    patching:
        patch_size: 224
        stride: 112
    selected_channels: null
augmentation:
    horizontal_flip:
        p: 0.5
    random_rotate_90:
        p: 0.5
    shift_scale_rotate:
        p: 0.5
        shift_limit: 0.0625
        scale_limit: 0.1
        rotate_limit: 15
    random_brightness_contrast:
        p: 0.5
model:
    name: GeminiUNetV2
    params:
        in_channels: 5
        num_classes: 6
        initial_filters: 32
        depth: 5
        dropout_rate: 0.2
        bilinear: false
        sac_params:
            reduced_depth: 3
            channels: 32
            use_sea: true
        band_selector_config:
            original_in_channels: 25
            num_selected_bands: 5
loss:
    name: CombinedLoss
    params:
        alpha: 0.4
        beta: 0.6
training:
    num_epochs: 300
    batch_size: 32
    use_amp: true
    early_stopping_patience: 80
optimizer:
    name: AdamW
    params:
        lr: 0.001
        weight_decay: 0.0001
scheduler:
    name: CosineAnnealingLR
    params:
        T_max: 300
        eta_min: 1.0e-06
