"""
Implementation of ASRAN with a Learnable Band Selector (LBS) using Gumbel-Softmax.
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
from .backbones import StandardUNet

# ============================================================
# Learnable Band Selector
# ============================================================

class LearnableBandSelector(nn.Module):
    """
    Selects the top-k bands from the input using a learnable Gumbel-Softmax mechanism.
    This is a "hard" selection mechanism that is differentiable.
    """
    def __init__(self, in_channels: int, num_select_bands: int, temperature: float = 1.0):
        super(LearnableBandSelector, self).__init__()
        if num_select_bands > in_channels:
            raise ValueError(f"num_select_bands ({num_select_bands}) cannot be greater than in_channels ({in_channels}).")
        self.in_channels = in_channels
        self.num_select_bands = num_select_bands
        self.temperature = temperature
        
        # Learnable logits for each band. Higher logit means higher probability of being selected.
        self.logits = nn.Parameter(torch.randn(in_channels))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # x shape: (B, C, H, W)
        
        if self.training:
            # Use Gumbel-TopK trick for differentiable hard selection
            # Note: We use the straight-through Gumbel-TopK trick implicitly.
            # The gradient flows through the continuous probabilities generated by softmax,
            # while the forward pass uses a hard, non-differentiable top-k.
            # PyTorch's autograd handles this via the continuous proxy variables.
            gumbel_noise = -torch.log(-torch.log(torch.rand_like(self.logits)))
            perturbed_logits = (self.logits + gumbel_noise) / self.temperature
            _, top_k_indices = torch.topk(perturbed_logits, self.num_select_bands, dim=-1)
        else:
            # During inference, just pick the top-k bands based on the learned logits
            _, top_k_indices = torch.topk(self.logits, self.num_select_bands, dim=-1)

        # Gather the channels based on the selected indices
        output = torch.index_select(x, dim=1, index=top_k_indices)
        
        return output

# ============================================================
# ASRAN-LBS Main Architecture
# ============================================================

class ASRAN_LBS(nn.Module):
    """
    ASRAN with Learnable Band Selector.
    It first selects k bands from the input and then feeds them to the standard U-Net backbone.
    The backbone can optionally include a Spectral Reconstruction Head.
    """
    def __init__(self, in_channels: int, num_classes: int, num_select_bands: int, base_filters: int = 16, temperature: float = 1.0, use_sr_head: bool = False):
        super(ASRAN_LBS, self).__init__()
        self.band_selector = LearnableBandSelector(
            in_channels=in_channels, 
            num_select_bands=num_select_bands, 
            temperature=temperature
        )
        
        # Use the standardized U-Net backbone, passing the SR head flag
        self.segmentation_network = StandardUNet(
            in_channels=num_select_bands, 
            num_classes=num_classes, 
            base_filters=base_filters,
            use_asa=True, # ASRAN-LBS always uses Spatial Attention as per design
            use_sr_head=use_sr_head,
            sr_out_channels=in_channels # Reconstruct original number of channels
        )

    def forward(self, x: torch.Tensor):
        # 1. Select bands dynamically
        selected_bands = self.band_selector(x)
        
        # 2. Perform segmentation (and possibly reconstruction) on the selected bands
        # The backbone will return either a tensor or a dict
        outputs = self.segmentation_network(selected_bands)
        
        # If the SR head is used, the backbone returns a dict.
        # We need to add the original input to the dict for loss calculation.
        if isinstance(outputs, dict):
            outputs['original_input'] = x
            return outputs
        
        # Otherwise, just return the segmentation logits
        return outputs